const AUTHENTICATE_ROUTE = {};

const APP_ROUTE = {
  MAIN_TAB: 'MAIN_TAB',
};

const HOME_ROUTE = {
  ROOT: 'HOME_ROUTE',
  HOME_SCREEN: 'HOME_SCREEN',
};

const TAB_NAVIGATION_ROOT = {
  HOME_ROUTE,
};

export {AUTHENTICATE_ROUTE, APP_ROUTE, TAB_NAVIGATION_ROOT};
